# Generated by Django 5.1.1 on 2024-11-29 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('oil_type', models.CharField(max_length=255)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('oil_lifetime_distance', models.PositiveIntegerField(blank=True, help_text='Estimated lifetime of the oil in kilometers', null=True)),
                ('next_change_mileage', models.PositiveIntegerField(blank=True, help_text='Mileage at which next oil change is due', null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_changes', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_changes', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
