# Generated by Django 5.1.1 on 2024-09-24 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start_data__lte', models.F('end_data'))), name='start_date_before_end_date')],
            },
        ),
    ]
